/*
 * PenentuJumlahHari.java
 *
 * Created on 09 Desember 2021, 20:44
 */

package penghitunganjumlahhari;

import java.io.BufferedWriter;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author  erwin
 */
public class PenentuJumlahHari extends javax.swing.JFrame {

    /** Creates new form PenentuJumlahHari */
    public PenentuJumlahHari() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TahunLabel = new javax.swing.JLabel();
        TahunTF = new javax.swing.JTextField();
        BulanLabel = new javax.swing.JLabel();
        BulanCB = new javax.swing.JComboBox();
        jmlharilabel = new javax.swing.JLabel();
        hitungBT = new javax.swing.JButton();
        HapusBT = new javax.swing.JButton();
        SimpanBT = new javax.swing.JButton();
        keluarBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TahunLabel.setText("Tahun");

        BulanLabel.setText("Bulan");

        BulanCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Dsember" }));
        BulanCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BulanCBActionPerformed(evt);
            }
        });

        jmlharilabel.setText("Jumlah hari adalah=");

        hitungBT.setText("Hitung");
        hitungBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungBTActionPerformed(evt);
            }
        });

        HapusBT.setText("Hapus");
        HapusBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusBTActionPerformed(evt);
            }
        });

        SimpanBT.setText("Simpan");
        SimpanBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanBTActionPerformed(evt);
            }
        });

        keluarBT.setText("Keluar");
        keluarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jmlharilabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BulanLabel)
                            .addComponent(TahunLabel))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BulanCB, 0, 176, Short.MAX_VALUE)
                            .addComponent(TahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(132, 132, 132))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hitungBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HapusBT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SimpanBT)
                .addGap(18, 18, 18)
                .addComponent(keluarBT)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TahunLabel)
                    .addComponent(TahunTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BulanLabel)
                    .addComponent(BulanCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jmlharilabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitungBT)
                    .addComponent(HapusBT)
                    .addComponent(SimpanBT)
                    .addComponent(keluarBT))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void BulanCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulanCBActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_BulanCBActionPerformed

private void hitungBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungBTActionPerformed
// TODO add your handling code here:
    if(TahunTF.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Error: isian tahun kosong!",
                "Error: isian tahun kosong!", JOptionPane.WARNING_MESSAGE);
    }else{
        int tahun = Integer.parseInt(TahunTF.getText());
        int jumlahhari;
        if(BulanCB.getSelectedItem().equals("Februari")){
            if(((tahun % 4 == 0) && ! (tahun % 100 == 0)) || (tahun % 400 == 0))
                jumlahhari =29;
            else jumlahhari = 28;
            
        }else{
            jumlahhari= 31;
        }
        jmlharilabel.setText("Jumlah hari pada bulan " +
                BulanCB.getSelectedItem() +
                " tahun " + tahun + " adalah " + jumlahhari);
    }
}//GEN-LAST:event_hitungBTActionPerformed

private void SimpanBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanBTActionPerformed
// TODO add your handling code here:
    try{
        //buatFile
        BufferedWriter out = new BufferedWriter (new FileWriter ("Jjumlahhari.txt"));
        //simpan ke file
        out.write(jmlharilabel.getText());
        //Tampilkan dialog bila berhasil
        JOptionPane.showMessageDialog(null,"Berhasil Disimpan dalam File");
        //tutup output stream
        out.close();
        
    } catch (Exception e) {//catch exception if any
        System.err.println("Error: " + e.getMessage());
    }
}//GEN-LAST:event_SimpanBTActionPerformed

private void keluarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarBTActionPerformed
// TODO add your handling code here:
    System.exit(0);
}//GEN-LAST:event_keluarBTActionPerformed

private void HapusBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusBTActionPerformed
// TODO add your handling code here:
    jmlharilabel.setText("");
    TahunTF.setText("");
    BulanCB.setSelectedItem("Januari");
}//GEN-LAST:event_HapusBTActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenentuJumlahHari().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox BulanCB;
    private javax.swing.JLabel BulanLabel;
    private javax.swing.JButton HapusBT;
    private javax.swing.JButton SimpanBT;
    private javax.swing.JLabel TahunLabel;
    private javax.swing.JTextField TahunTF;
    private javax.swing.JButton hitungBT;
    private javax.swing.JLabel jmlharilabel;
    private javax.swing.JButton keluarBT;
    // End of variables declaration//GEN-END:variables

}
